// <auto-generated />
using System;
using BulkyBook.WebUI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBook.WebUI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220929120900_Add_Book")]
    partial class Add_Book
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BulkyBook.WebUI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Publisher");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("SubCategoryId");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Writer");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Üç Kız Kardeş",
                            Price = 23.40m,
                            Publisher = "İş Bankası Kültür Yayınları",
                            SubCategoryId = 1,
                            Writer = "Anton Pavloviç Çehov"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bir Çöküşün Öyküsü",
                            Price = 16.20m,
                            Publisher = "İş Bankası Kültür Yayınları",
                            SubCategoryId = 2,
                            Writer = "Stefan Zweig"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Esen TYT Matematik Orta İleri Düzey Soru Bankası",
                            Price = 45.90m,
                            Publisher = "Esen Yayınları",
                            SubCategoryId = 3,
                            Writer = "Nevzat Asma, Halit Bıyık"
                        },
                        new
                        {
                            Id = 4,
                            Name = "2022 DGS 6 Muhteşem Fasikül Fasikül Deneme",
                            Price = 53.40m,
                            Publisher = "Tasarı Eğitim Yayınları",
                            SubCategoryId = 4,
                            Writer = "Özgen Bulut"
                        });
                });

            modelBuilder.Entity("BulkyBook.WebUI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDateTime");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2022, 9, 29, 15, 9, 0, 368, DateTimeKind.Local).AddTicks(8015),
                            DisplayOrder = 11,
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2022, 9, 29, 15, 9, 0, 368, DateTimeKind.Local).AddTicks(8027),
                            DisplayOrder = 22,
                            Name = "Preparation for Exams"
                        });
                });

            modelBuilder.Entity("BulkyBook.WebUI.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Story"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Novel"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "TYT"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "DGS"
                        });
                });

            modelBuilder.Entity("BulkyBook.WebUI.Models.Book", b =>
                {
                    b.HasOne("BulkyBook.WebUI.Models.SubCategory", "SubCategory")
                        .WithMany("Books")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("BulkyBook.WebUI.Models.SubCategory", b =>
                {
                    b.HasOne("BulkyBook.WebUI.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BulkyBook.WebUI.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("BulkyBook.WebUI.Models.SubCategory", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
